import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Compass, Video, MessageCircle, UserRound, SlidersHorizontal, RefreshCw, X, Sparkles, Map, Users, Smartphone, NotebookPen, Settings2, Send, Heart, Shield, Wifi, ChevronRight} from 'lucide-react';
import './styles.css';

const seedPeople=[
 {id:'NOVA-1024', distance:'1 km', tag:'开放关系 · 夜猫子', xp:'喜欢慢热、暧昧拉扯', image:'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&q=80', online:true},
 {id:'MICA-7781', distance:'3 km', tag:'摄影 · 健身 · 直球', xp:'被看见，也喜欢探索边界', image:'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&q=80', online:true},
 {id:'KAI-4490', distance:'5 km', tag:'音乐节 · 低调', xp:'从聊天开始，慢慢靠近', image:'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=800&q=80', online:false},
];
const videos=[
 {author:'NOVA-1024', title:'凌晨两点的霓虹雨', desc:'镜头从一盏蓝色招牌开始，雨水沿着玻璃缓慢滑落。她把手机靠在窗边，短暂地望向镜头，像是在等一个不会迟到的人。背景音乐很轻，城市的低频噪音反而成为主旋律。画面中偶尔掠过一辆出租车，车灯把整条街切成明暗两半。最后她写下一行字：今晚想认识一个有趣的人。', tags:['夜景','氛围感','暧昧'], likes:328},
 {author:'MICA-7781', title:'周末公园即兴舞', desc:'阳光落在草地上，镜头跟着一双白色球鞋移动。音乐一响，身边的人自然围成一个小圈，动作不算标准，却有种松弛的快乐。中间有几次镜头失焦，反而让笑声和风吹树叶的声音更清楚。结尾处他对着镜头挥手，字幕写着：下次一起跳。', tags:['舞蹈','周末','生活'], likes:186},
];

function App(){
 const [mode,setMode]=useState('sim'); const [tab,setTab]=useState('nearby'); const [settingsOpen,setSettingsOpen]=useState(false); const [refresh,setRefresh]=useState(0); const [onboarding,setOnboarding]=useState(()=>!localStorage.getItem('sim-onboarded'));
 const [profile,setProfile]=useState(()=>JSON.parse(localStorage.getItem('sim-profile')||'{"name":"林昼","age":27,"gender":"男","xp":"好奇、慢热、喜欢深夜聊天"}'));
 const [world,setWorld]=useState(()=>localStorage.getItem('sim-world')||'近未来都市，人与AI共存，关系由真诚和选择推动。');
 const [api,setApi]=useState(()=>localStorage.getItem('sim-api')||'');
 useEffect(()=>localStorage.setItem('sim-profile',JSON.stringify(profile)),[profile]); useEffect(()=>localStorage.setItem('sim-world',world),[world]); useEffect(()=>localStorage.setItem('sim-api',api),[api]);
 const nav=mode==='sim'?[['nearby','附近',Compass],['xp','XP标签',Sparkles],['video','视频',Video],['chat','聊天',MessageCircle],['me','个人',UserRound]]:[['journal','AI记事',NotebookPen],['relations','人际',Users],['attributes','个人属性',SlidersHorizontal],['phone','手机',Smartphone],['map','地图',Map]];
 const title=nav.find(n=>n[0]===tab)?.[1]||'';
 return <div className="app-shell">
  <aside className="sidebar"><div className="brand"><div className="brand-mark">◒</div><div><strong>NOCTURNE</strong><span>AI SOCIAL SIM</span></div></div><div className="mode-switch"><button className={mode==='sim'?'active':''} onClick={()=>{setMode('sim');setTab('nearby')}}>模拟器</button><button className={mode==='real'?'active':''} onClick={()=>{setMode('real');setTab('journal')}}>现实世界</button></div><nav>{nav.map(([id,label,Icon])=><button key={id} className={tab===id?'selected':''} onClick={()=>setTab(id)}><Icon size={17}/><span>{label}</span>{id==='chat'&&<em>3</em>}</button>)}</nav><div className="sidebar-bottom"><button onClick={()=>setSettingsOpen(true)}><Settings2 size={17}/>系统配置</button><div className="connection"><Wifi size={14}/><span>本地模拟 · 已保存</span></div></div></aside>
  <main className="main"><header><div><div className="breadcrumb">{mode==='sim'?'SIMULATOR':'REALITY'} <span>/</span> {title.toUpperCase()}</div><h1>{title}</h1></div><div className="header-actions"><button className="icon-btn" title="刷新生成" onClick={()=>setRefresh(x=>x+1)}><RefreshCw size={18}/></button><button className="icon-btn" title="系统配置" onClick={()=>setSettingsOpen(true)}><SlidersHorizontal size={18}/></button><button className="exit-btn" onClick={()=>setMode(mode==='sim'?'real':'sim')}>{mode==='sim'?'退出模拟器':'返回模拟器'} <ChevronRight size={15}/></button></div></header><div className="content">{mode==='sim'?<Simulator tab={tab} refresh={refresh} profile={profile}/>:<Reality tab={tab} profile={profile} setProfile={setProfile} world={world} setWorld={setWorld}/>}</div></main>
  {settingsOpen&&<Settings onClose={()=>setSettingsOpen(false)} world={world} setWorld={setWorld} api={api} setApi={setApi}/>} 
  {onboarding&&<Onboarding profile={profile} setProfile={setProfile} onDone={()=>{localStorage.setItem('sim-onboarded','1');setOnboarding(false)}}/>}
 </div>
}
function Onboarding({profile,setProfile,onDone}){const [span,setSpan]=useState('日');return <div className="overlay"><div className="onboarding"><p className="eyebrow">WELCOME TO NOCTURNE</p><h2>先定义你的现实身份</h2><p className="onboarding-copy">这些设定只属于现实世界，不会覆盖你的模拟器偏好。</p><div className="form-grid"><label>姓名<input value={profile.name} onChange={e=>setProfile({...profile,name:e.target.value})}/></label><label>年龄<input type="number" value={profile.age} onChange={e=>setProfile({...profile,age:e.target.value})}/></label><label>性别<select value={profile.gender} onChange={e=>setProfile({...profile,gender:e.target.value})}><option>男</option><option>女</option><option>非二元</option></select></label><label>时间跨度<select value={span} onChange={e=>setSpan(e.target.value)}><option>日</option><option>周</option><option>月</option></select></label></div><button className="primary-btn" onClick={onDone}>进入世界 <ChevronRight size={15}/></button></div></div>}

function Simulator({tab,refresh,profile}){ if(tab==='nearby'||tab==='xp') return <Nearby refresh={refresh} profile={profile}/>; if(tab==='video') return <VideoFeed refresh={refresh}/>; if(tab==='chat') return <Chats/>; return <SimProfile profile={profile}/> }
function Nearby({refresh,profile}){const people=useMemo(()=>seedPeople.map((p,i)=>({...p,id:refresh?`${p.id.slice(0,-1)}${(refresh+i)%9}`:p.id})),[refresh]); return <section><div className="section-intro"><div><p className="eyebrow">基于你的偏好 · {profile.xp}</p><h2>距离你最近的人</h2></div><button className="ghost-btn" onClick={()=>location.reload()}><RefreshCw size={15}/>重新扫描</button></div><div className="scanline"><span className="pulse"></span>雷达扫描中 <b>12 位用户在线</b><span className="scan-distance">半径 5 km</span></div><div className="people-grid">{people.map(p=><article className="person-card" key={p.id}><div className="person-image" style={{backgroundImage:`url(${p.image})`}}><span className={p.online?'online':'offline'}>{p.online?'在线':'刚刚离开'}</span><button className="heart"><Heart size={16}/></button></div><div className="person-body"><div className="person-top"><strong>{p.id}</strong><span>{p.distance}</span></div><div className="tag">{p.tag}</div><p>{p.xp}</p><div className="person-actions"><button className="primary-btn">打招呼 <Send size={14}/></button><button className="secondary-btn">查看资料</button></div></div></article>)}</div></section>}
function VideoFeed({refresh}){return <section><div className="section-intro"><div><p className="eyebrow">为你推荐 · 第 {refresh+1} 组</p><h2>正在发生</h2></div><button className="ghost-btn"><RefreshCw size={15}/>刷新视频</button></div><div className="video-list">{videos.map((v,i)=><article className="video-card" key={v.title}><div className="video-thumb" style={{backgroundImage:`url(${i?'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=1000&q=80':'https://images.unsplash.com/photo-1519608487953-e999c86e7455?w=1000&q=80'})`}}><div className="play">▶</div><span>0:{42+i*11}</span></div><div className="video-copy"><div className="video-author"><div className="mini-avatar">{v.author[0]}</div><strong>{v.author}</strong><button className="follow">+ 关注</button></div><h3>{v.title}</h3><p>{v.desc}</p><div className="tags">{v.tags.map(t=><span key={t}>#{t}</span>)}<span className="likes">♡ {v.likes}</span></div></div></article>)}</div></section>}
function Chats(){return <section><div className="section-intro"><div><p className="eyebrow">3 条未读消息</p><h2>聊天</h2></div><button className="ghost-btn"><MessageCircle size={15}/>新建对话</button></div><div className="chat-layout"><div className="chat-list">{['NOVA-1024','MICA-7781','陌生人 · 新视频'].map((name,i)=><div className={`chat-row ${i===0?'active':''}`} key={name}><div className="mini-avatar">{name[0]}</div><div><strong>{name}</strong><p>{i===0?'你今晚有空吗？':i===1?'分享了一张照片':'发来一条新视频'}</p></div><span>{i===0?'刚刚':'12:4'+i}</span></div>)}</div><div className="chat-empty"><MessageCircle size={32}/><h3>选择一个对话</h3><p>从左侧打开聊天，开始你的下一段关系。</p></div></div></section>}
function SimProfile({profile}){return <section><div className="profile-hero"><div className="profile-avatar">{profile.name[0]}</div><div><p className="eyebrow">模拟器身份</p><h2>{profile.name}</h2><p>{profile.age} 岁 · {profile.gender}</p></div><span className="vip">VIP · 双向选择</span></div><div className="profile-fields"><div><label>个人标签</label><p>深夜、慢热、城市漫游</p></div><div><label>个人 XP</label><p>{profile.xp}</p></div><div><label>可见范围</label><p>附近 5 km · 所有人可见</p></div></div></section>}
function Reality({tab,profile,setProfile,world,setWorld}){if(tab==='journal')return <section><div className="section-intro"><div><p className="eyebrow">今日 · 2026.08.20</p><h2>AI 记事</h2></div><button className="primary-btn"><Sparkles size={15}/>生成今日剧情</button></div><div className="journal-card"><div className="journal-date">20 <span>八月<br/>星期四</span></div><div><h3>雨停之后，去见一个新朋友</h3><p>傍晚 19:30，你在旧港区的唱片店门口遇见 NOVA-1024。她记得你喜欢低饱和的爵士乐，提议一起走到河边。今晚的城市很安静，适合把关系从屏幕带到现实。</p><div className="journal-meta">线下约会 · 关系推进 +8 · 氛围值 72</div></div></div></section>; if(tab==='relations')return <section><div className="section-intro"><div><p className="eyebrow">连接你的世界</p><h2>人际关系</h2></div><button className="ghost-btn"><Users size={15}/>AI 生成人物</button></div><div className="relation-list">{[['NOVA-1024','暧昧对象','关系值 68','♀'],['MICA-7781','朋友','关系值 42','♂'],['林澈','旧识','关系值 21','♀']].map(r=><div className="relation-row" key={r[0]}><div className="relation-avatar">{r[3]}</div><div><strong>{r[0]}</strong><p>{r[1]} · {r[2]}</p></div><div className="relation-bar"><span style={{width:r[2].replace(/[^0-9]/g,'')+'%'}}></span></div></div>)}</div></section>; if(tab==='attributes')return <section><div className="section-intro"><div><p className="eyebrow">现实身份 · 可随时调整</p><h2>个人属性</h2></div><span className="saved">已自动保存</span></div><div className="form-grid"><label>姓名<input value={profile.name} onChange={e=>setProfile({...profile,name:e.target.value})}/></label><label>年龄<input type="number" value={profile.age} onChange={e=>setProfile({...profile,age:e.target.value})}/></label><label>性别<select value={profile.gender} onChange={e=>setProfile({...profile,gender:e.target.value})}><option>男</option><option>女</option><option>非二元</option></select></label><label>时间跨度<select><option>日</option><option>周</option><option>月</option></select></label></div></section>; if(tab==='phone')return <section><div className="section-intro"><div><p className="eyebrow">设备 · 微信</p><h2>手机</h2></div><span className="phone-status"><span className="pulse"></span>在线</span></div><div className="phone-frame"><div className="phone-head">微信 <span>9:41</span></div><div className="phone-chat"><div className="wechat-avatar">N</div><div><strong>NOVA-1024</strong><p>你今晚有空吗？</p></div><span>刚刚</span></div><div className="phone-chat"><div className="wechat-avatar alt">M</div><div><strong>MICA-7781</strong><p>发来一张照片</p></div><span>12:42</span></div></div></section>; return <section><div className="section-intro"><div><p className="eyebrow">世界生成器</p><h2>地图</h2></div><button className="primary-btn"><Sparkles size={15}/>生成地图</button></div><div className="map-card"><div className="map-grid"></div><div className="map-pin pin-a">你</div><div className="map-pin pin-b">NOVA</div><div className="map-label">旧港区 · 夜间开放</div></div></section>}
function Settings({onClose,world,setWorld,api,setApi}){const [draft,setDraft]=useState(world);return <div className="overlay"><div className="settings-drawer"><div className="drawer-head"><div><p className="eyebrow">全局设置</p><h2>系统配置</h2></div><button className="icon-btn" onClick={onClose}><X size={18}/></button></div><div className="setting-section"><label>API Endpoint<input placeholder="https://api.openai.com/v1" value={api} onChange={e=>setApi(e.target.value)}/></label><label>世界观设定<textarea value={draft} onChange={e=>setDraft(e.target.value)} rows="6"/></label><button className="primary-btn" onClick={()=>{setWorld(draft);onClose()}}>保存配置 <Shield size={14}/></button></div><div className="setting-note"><Sparkles size={16}/><p>当前为本地模拟模式。配置 API 后，刷新按钮可以接入真实的图片描述、人物生成与剧情生成服务。</p></div></div></div>}

createRoot(document.getElementById('root')).render(<App/>);
